language: ruby
rvm:
- 2.3.3

git:
  depth: 2147483647

install: 
  - npm install -g bower
  - bower install
  - bundle install

script: jekyll build ./_site 

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: pages
  skip_cleanup: true
  on:
    branch: master
  local_dir: app/_site  